# ============================================================================
# AGENT & TOOL CALLING - Single-turn and multi-turn agent modes
# ============================================================================
# Purpose: Generate datasets for training tool-using agents
# Usage: deepfabric start examples/configs/04-agent-tools.yaml
# ============================================================================
#
# Agent modes enable tool-calling capabilities:
#
# 1. SINGLE_TURN - Agent completes task in one interaction
#    Use for: Function calling, simple tool usage, API interactions
#
# 2. MULTI_TURN - Multi-step conversations with tool usage
#    Use for: Complex tasks requiring multiple tools, XLAM format training
#
# Requirements:
# - Must use conversation_type: "chain_of_thought"
# - Must specify reasoning_style
# - Must configure available_tools
#
# ============================================================================

dataset_system_prompt: |
  You are an AI assistant with access to various tools and functions.
  When given a task:
  1. Analyze what tools are needed
  2. Execute tools with proper parameters
  3. Interpret results and provide a clear answer

topic_tree:
  topic_prompt: "Real-world tasks requiring tool usage (weather, calculations, web search, time)"
  provider: "openai"
  model: "gpt-4o"
  degree: 2
  depth: 2
  save_as: "topics.jsonl"

data_engine:
  generation_system_prompt: |
    Generate examples of tool usage with clear reasoning.
    Show why tools are chosen and how results are interpreted.

  instructions: "Create realistic scenarios requiring tool usage to complete tasks."

  # Chain of thought with agent mode
  conversation_type: "chain_of_thought"
  reasoning_style: "agent"

  # Single-turn agent configuration
  agent_mode: "single_turn"

  # Built-in tools available for use
  available_tools:
    - "get_weather"      # Get weather for a location
    - "calculate"        # Perform calculations
    - "search_web"       # Search the web
    - "get_time"         # Get current time in timezone

  max_tools_per_query: 3  # Maximum tools per example

  provider: "openai"
  model: "gpt-4o"
  temperature: 0.8

dataset:
  save_as: "agent-tools-dataset.jsonl"
  creation:
    num_steps: 2
    batch_size: 2
    sys_msg: true
