# ============================================================================
# QUICKSTART CONFIG
# ============================================================================
# Purpose: Simple config to get started with DeepFabric
# Output format: Standard conversations format (most versatile)
# Usage: deepfabric generate examples/quickstart.yaml
# ============================================================================

# Define your dataset's purpose
dataset_system_prompt: |
  You are a helpful AI assistant.
  Create high-quality question-answer pairs for training.

# Topic generation settings
topic_tree:
  topic_prompt: "Vehicle mechanics and advancements"  # Change this to your domain
  provider: "openai"  # or "anthropic", "gemini", "ollama"
  model: "gpt-4o"
  temperature: 0.8
  degree: 2  # Number of subtopics per branch
  depth: 2  # Tree depth (2-3 is usually enough)
  save_as: "topics.jsonl"

# Data generation settings
data_engine:
  generation_system_prompt: "Create informative Q&A pairs that are helpful and accurate."
  instructions: "Generate diverse questions and detailed answers about vehicle mechanics and advancements."
  provider: "openai"
  model: "gpt-4o"
  temperature: 0.7
  conversation_type: "basic"  # Options: basic, cot_structured, cot_freetext

# Dataset configuration
dataset:
  creation:
    num_steps: 2  # Number of generation steps
    batch_size: 2
    sys_msg: false
  save_as: "basic-dataset.jsonl"
